### ISSUE TITLE
Usability: reaction from action

### ISSUE THREAD

**Issue by neloe** [VSMDURGAPRASAD/GDP_Group4#26]
When I try to register a new user (fake email account), the page flickers but does not report success or failure.  I am unable to log in with new credentials, and do not know if it's because the account doesn't exist or some other reason.  the javascript console does report that some css files are 404, but that shouldn't be causing this particular issue

**Comment by VSMDURGAPRASAD** [comment]
Added that reaction mechanism when user enter their passwords valid error message thrown .And we linked to all pages
