### ISSUE TITLE
Broken Functionality: Creating Class with roster

### ISSUE THREAD

**Issue by neloe** [VSMDURGAPRASAD/GDP_Group4#32]
Using a csv containing the following:

a@b.com, a
b@c.com, b
c@c.com, d

The class is allowed to be saved, but the card shows me that there are two students, and they are empty.  Are there other limitations on the class input roster?  if so they are not well communicated

**Comment by VSMDURGAPRASAD** [comment]
Added a Correct Roster with format name ,email in the top and below are the names
